apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\Users\kot\tools\kompose\kompose-windows-amd64.exe convert
    kompose.version: 1.32.0 (765fde254)
  labels:
    io.kompose.service: reverse-proxy
  name: reverse-proxy
spec:
  ports:
    - name: "8000"
      port: 8000
      targetPort: 80
  selector:
    io.kompose.service: reverse-proxy
