apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Users\kot\tools\kompose\kompose-windows-amd64.exe convert
    kompose.version: 1.32.0 (765fde254)
  labels:
    io.kompose.service: reverse-proxy
  name: reverse-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: reverse-proxy
  template:
    metadata:
      annotations:
        kompose.cmd: C:\Users\kot\tools\kompose\kompose-windows-amd64.exe convert
        kompose.version: 1.32.0 (765fde254)
      labels:
        io.kompose.network/js-belote-default: "true"
        io.kompose.service: reverse-proxy
    spec:
      containers:
        - image: reverse-proxy
          name: reverse-proxy
          ports:
            - containerPort: 80
              hostPort: 8000
              protocol: TCP
      restartPolicy: Always
